### ISSUE TITLE
Missing incident history on status.scarf.sh

### ISSUE THREAD

**Issue by wallrj** [scarf-sh/gateway#26]
We are considering [adopting scarf.sh gateway for the cert-manager Docker images](https://github.com/cert-manager/cert-manager/pull/6667),
and one of our reasons is to improve the availability of the Docker images in case of an outage with the backing registry.
Therefore I want to know what is the availability track record of the scarf gateway.

I see five outages in the three months between 1 September 2023 and 1 December 2023 in the uptime calendar, but I can't find a record of these incidents in the uptime history so it's difficult to know how serious these were.

![image](https://github.com/scarf-sh/gateway/assets/978965/e98cdd7e-bb61-4c4d-bbdb-a1922d2ae654)
![image](https://github.com/scarf-sh/gateway/assets/978965/af67d06c-58ab-4cbd-ac57-6090c2079951)

https://status.scarf.sh/788363216/calendar

**Comment by hollyos** [comment]
Hi @wallrj. We're currently in the process of switching our status page provider. This exact reason was a major factor in our decision to switch. We should be going live with the new status page, with historical records by next week. Will update once the change over is live.

**Comment by hollyos** [comment]
@wallrj We have officially switched over our [status page](https://status.scarf.sh) provider. The new status page has the historical outages along with better incident details.
![SCR-20240223-irb](https://github.com/scarf-sh/gateway/assets/4097509/db9599d6-0e94-4440-bb25-72545f44f6e8)
![SCR-20240223-iry](https://github.com/scarf-sh/gateway/assets/4097509/8da48f08-069c-49fd-bc37-40bb9236c1b9)
